version: "3.8"
services:
  contenedor-civilo-mysql: # Nombre de contenedor MYSQL
    container_name: contenedor-civilo-mysql
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: civilo_roller_db
    ports:
      - 33060:3306

  civilo_roller_app: 
    container_name: contenedor-civilo-roller-backend
    image: gerardoluceroc/imagen_civilo_roller_backend:latest
    ports:
      - "8080:8080"
    environment:
    #Estas variables de entorno si bien estan escritas, aun no se ponen en el backend de spring boot
      - DB_URL=jdbc:mysql://contenedor-civilo-mysql:3306/civilo_roller_db
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - contenedor-civilo-mysql

  contenedor-frontend-civilo-roller: 
    container_name: contenedor-frontend-civilo-roller
    image: gerardoluceroc/imagen-frontend-civilo-roller:latest
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - civilo_roller_app
    

    
